### ISSUE TITLE
On many of the darker themes, the highlighter background colour is almost invisible

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [ihodev/sublime-boxy#176]
**The problem / steps to reproduce**

Install the boxy theme and choose one of these colour-schemes for it: Ocean; Tomorrow; or (to a lesser extent) Monokai.

Write a line of text. Highlight it. Try to see that you *have* highlighted it.

**Suggested fix**

Make the background colour stand out a bit more, presumably by making it slightly lighter.

**My environment**

I have this problem on a Windows computer and on a Linux computer.

**Comment by michaelblyons** [comment]
I think this is my fault from #81

**Comment by ACinnamonUserInUK** [comment]
@michaelblyons: it's good of you to confess, though you are not solely responsible (and here should I call you @ihodev?*). The next step is . . rectification. Please?

* I don't really know what's caused the problem. Yet, I submit that it is a problem and I would like it fixed. I imagine many others would like it remedied too.

**Comment by ihodev** [comment]
Many users like current implementation and I don't want to provide another defaults. Just update it manually as described [here](https://github.com/ihodev/sublime-boxy/wiki/Settings#advanced). Selection color depends on your display settings, that's why on some monitors it looks good, on others it looks bad. You can save an updated color scheme to the user folder.

Duplicates #74.

P.S. Currently I'm working on the new theme. It will allow you to do such customization easily. I'll be back when I'll have some news for you.

**Comment by ACinnamonUserInUK** [comment]
@ihodev, thank you very much. Yet, I still need a little more help please. I've managed to install the PackageResourceViewer, and managed to load for editing the Boxy-Ocean theme. However, I can't see what setting(s) to change to alter the colour of selected text.

**Comment by ihodev** [comment]
@ACinnamonUserInUK See [this](https://github.com/ihodev/sublime-boxy/blob/dev/schemes/Boxy%20Ocean.tmTheme#L74). Also if you want to change foreground color of the selection you can add:

```
<key>selectionForeground</key>
<string>#ff00ff</string>
```
