### ISSUE TITLE
Tweaking the colour of the tab-bar/sidebar background?

### ISSUE THREAD

**Issue by hughwilliams94** [ihodev/sublime-boxy#180]
Using the tomorrow theme (Which I love, thank you very much!) I would like to adjust the background colour of the tab bar and side pane to match my system panel for a bit of continuity in maximized windows. Which values should I be adjusting?

![bug](https://user-images.githubusercontent.com/15379654/27087651-7a63cf12-504d-11e7-814a-bcf5655ee488.png)

**Comment by ihodev** [comment]
Hello @hughwilliams94 ! That's not so simple task, because there are many color overrides in the theme. You can try to replace colors in `Boxy Tomorrow`: `35, 36, 38` -> `49, 54, 59`. Also [see this](https://forum.sublimetext.com/t/boxy-the-most-hackable-theme-for-sublime-text-3/20564/121) for more details.

**Comment by hughwilliams94** [comment]
Bingo!
