### ISSUE TITLE
Close "x" Position

### ISSUE THREAD

**Issue by umarmughal** [ihodev/sublime-boxy#199]
Hi, its a small issue but needs to be fixed, the "x" for sidebar and tabs is not vertically center in Windows10, please fix if possible .. no doubt its the best sublime theme ever.

![x-position](https://user-images.githubusercontent.com/1124947/32984414-9d68f02a-ccbf-11e7-84ec-e552b4951f50.png)

**Comment by ihodev** [comment]
I don't have plans to support Boxy anymore. You can try [DA UI](https://packagecontrol.io/packages/DA%20UI) & [DA CS](https://packagecontrol.io/packages/DA%20CS) instead. It will be open sourced when I have some free time. Currently I'm very busy due to changing my job position and the stack I learn to.
