### ISSUE TITLE
Move dependent packages to github

### ISSUE THREAD

**Issue by kaiser101** [ihodev/sublime-boxy#202]
Some of the packages required by Boxy (python-jinja2, markupsafe) are in bitbucket, In some organizations bitbucket is blocked by the corporate proxy. Can we move these to github so they and subsequently Boxy theme can be installed?

**Comment by ihodev** [comment]
@kaiser101 I'm sorry for my long silence! I don't have plans to support Boxy anymore. You can try [DA UI](https://packagecontrol.io/packages/DA%20UI) & [DA CS](https://packagecontrol.io/packages/DA%20CS) instead. It doesn't require any dependencies and will be open sourced when I have some free time. Currently I'm very busy due to changing my job position and the stack I learn to.
