### ISSUE TITLE
Find panel's input field has smaller text

### ISSUE THREAD

**Issue by akatechis** [ihodev/sublime-boxy#203]
#### Expected Behavior
I would assume there is some sort of configuration option to let me control the size of the text inside the input field of a find panel.

#### Current Behavior
There does not seem to be such an option. I have tried all of the following options to no avail:

```
"theme": "Boxy Nova.sublime-theme",
"theme_font_xl": true,
"theme_find_panel_size_xl": true,
"theme_find_panel_font_xl": true,
"theme_find_panel_padding_xs": true,
"theme_find_panel_close_hidden": true,
"theme_find_panel_atomized": true,
"theme_tab_line_size_lg": true,
"theme_tab_selected_overlined": true,
"theme_tab_size_xl": true,
"theme_unified": true,
```

#### Your Environment
I'm on MacOS, using ST 3.0 Build 3143, with the latest boxy theme with the font face and unified theme addons.

![screen shot 2018-01-08 at 1 49 02 pm](https://user-images.githubusercontent.com/1058931/34687121-d02aec8c-f47b-11e7-8494-38f549a0968e.png)

**Comment by ihodev** [comment]
@akatechis I don't have plans to support Boxy anymore. You can try [DA UI](https://packagecontrol.io/packages/DA%20UI) & [DA CS](https://packagecontrol.io/packages/DA%20CS) instead. It supports a lot more customizations and will be open sourced when I have some free time. Currently I'm very busy due to changing my job position and the stack I learn to.

**Comment by akatechis** [comment]
Fair enough. Thank you for all your hard work, in creating these beautiful themes. Will take a look at your other themes.
